apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.service.name }}
  labels:
    app: {{ .Values.application.service.name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: {{ .Values.application.service.name }}
  selector:
    app: {{ .Values.application.service.name }}
  type: NodePort