apiVersion: apps/v1
kind: Deployment
metadata:
  name: milanuncios
  labels:
    app: milanuncios
spec:
  selector:
    matchLabels:
      app: milanuncios
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: milanuncios
      labels:
        app: milanuncios
    spec:
      containers:
      - name: java
        image: {{ .Values.application.image }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.database.pass }}
          - name: MYSQL_DATABASE
            value: {{ .Values.database.db }}