apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.service.name }}
  labels:
    app: {{ .Values.application.service.name }}
    type: db
spec:
  selector:
    matchLabels:
      type: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ .Values.database.service.name }}
      labels:
        app: {{ .Values.application.service.name }}
        type: db
    spec:
      containers:
      - name: database
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pass
          - name: MYSQL_DATABASE
            value: test
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: pvc-db-volume