apiVersion: apps/v1
kind: Deployment
metadata:
  name: milanuncios-db
  labels:
    app: milanuncios
    type: db
spec:
  selector:
    matchLabels:
      type: db
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: milanuncios-db
      labels:
        app: milanuncios
        type: db
    spec:
      containers:
      - name: database
        image: {{ .Values.database.image}}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.database.pass }}
          - name: MYSQL_DATABASE
            value: {{ .Values.database.db }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: pvc-db-volume