apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  labels:
    app: {{ .Values.database.service.name }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: {{ .Values.database.service.name }}
  selector:
    type: {{ .Values.database.service.name }}
  type: ClusterIP