apiVersion: networking.k8s.io/v1beta1
kind: Ingress  
metadata:  
  name: webs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: milanuncios
          servicePort: 8080